var cityList = [
 'Los Angeles',
 'Los Angeles County',
 'Agoura Hills',
 'Alhambra',
 'Arcadia',
 'Artesia',
 'Avalon',
 'Azusa',
 'Baldwin Park',
 'Bell',
 'Bell Gardens',
 'Bellflower',
 'Beverly Hills',
 'Bradbury',
 'Burbank',
 'Calabasas',
 'Carson',
 'Cerritos',
 'Claremont',
 'Commerce',
 'Compton',
 'Covina',
 'Cudahy',
 'Culver City',
 'Diamond Bar',
 'Downey',
 'Duarte',
 'El Monte',
 'El Segundo',
 'Gardena',
 'Glendale',
 'Glendora',
 'Hawaiian Gardens',
 'Hawthorne',
 'Hermosa Beach',
 'Hidden Hills',
 'Huntington Park',
 'Industry',
 'Inglewood',
 'Irwindale',
 'La Canada Flintridge',
 'La Habra Heights',
 'La Mirada',
 'La Puente',
 'La Verne',
 'Lakewood',
 'Lancaster',
 'Lawndale',
 'Lomita',
 'Long Beach',
// 'Los Angeles',
 'Lynwood',
 'Malibu',
 'Manhattan Beach',
 'Maywood',
 'Monrovia',
 'Montebello',
 'Monterey Park',
 'Norwalk',
 'Palmdale',
 'Palos Verdes Estates',
 'Paramount',
 'Pasadena',
 'Pico Rivera',
 'Pomona',
 'Rancho Palos Verdes',
 'Redondo Beach',
 'Rolling Hills',
 'Rolling Hills Estates',
 'Rosemead',
 'San Dimas',
 'San Fernando',
 'San Gabriel',
 'San Marino',
 'Santa Clarita',
 'Santa Fe Springs',
 'Santa Monica',
 'Sierra Madre',
 'Signal Hill',
 'South El Monte',
 'South Gate',
 'South Pasadena',
 'Temple City',
 'Torrance',
 'Unincorporated',
 'Vernon',
 'Walnut',
 'West Covina',
 'West Hollywood',
 'Westlake Village',
 'Whittier']